apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: t1
  namespace: compute
spec:
  # β(t1) = {security: 1, computation: 2}
  requirements:
    security: 1
    computation: 2
  # req(t1) = {d1, d2}
  datasets:
    - d1
    - d2