# This is an invalid TaskRequest used to test the validation webhook with external data provider.
# IMPORTANT:
# This task is based on the `examples/data/seed_datasets.json` and `examples/data/seed_contexts.json`
# data seeds, and the `examples/cluster-config.yaml` cluster configuration.
apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: emptystaticnodes
  namespace: compute
spec:
  issuer: issuerpublic
  requirements:
    security: 1
    computation: 2
  datasets:
    - d1static # kind-worker, kind-worker2, kind-worker4
    - d2static #kind-worker, kind-worker4
    - d3static # kind-worker3
  # empty intersection of static nodes
