# This is an invalid TaskRequest used to test the validation webhook with external data provider.
# IMPORTANT:
# This task is based on the `examples/data/seed_datasets.json` and `examples/data/seed_contexts.json`
# data seeds.
apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: emptygeostar
  namespace: compute
spec:
  issuer: issuer
  requirements:
    security: 1
    computation: 2
  datasets:
    - d1 # oecd
    - d3 # us
  geo: eu
# eu intersection us = []
