# This is an invalid TaskRequest used to test the validation webhook with external data provider.
# IMPORTANT:
# This task is based on the `examples/data/seed_datasets.json` and `examples/data/seed_contexts.json`
# data seeds.
apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: invalid
  # no namespace 'compute'
spec:
  issuer: issuernotexist # non-existent issuer
  requirements:
    security: 1
    computation: 99 # invalid level for 'computation' property
    dnotexist: 1 # non-existent property
  datasets:
    - d1 # valid dataset
    - d2 # valid dataset
    - d3ctx # dataset with "contexts": {Ferrari, Finance} -> not authorized for issuer-ford
    - dnotexist1 # non-existent dataset
    - dnotexist2 # non-existent dataset
    - dnotexistprop # dataset with "requirements": {"badprop1": 1, "badprop2": 3}
    - dnotexistlvl # dataset with "requirements": {"security": 99}
    - dnotexistgeo # dataset with "geo": "geonotexist"
  geo: geonotexist # non-existent geo
