  apiVersion: policydriven.unimi.it/v1alpha1
  kind: NodeProperty
  metadata:
    name: security
  spec:
    levels:
      # Level 1: cert = certC
      - disjunction:
          - clause:
              - key: cert
                operator: Eq
                values: ["certC"]
      # Level 2: (cert = certB) OR (isolation = strict)
      - disjunction:
          - clause:
              - key: cert
                operator: Eq
                values: ["certB"]
          - clause:
              - key: isolation
                operator: Eq
                values: ["strict"]
      # Level 3: (cert in {certA, certB}) AND (isolation = strict)
      - disjunction:
          - clause:
              - key: cert
                operator: In
                values: ["certA", "certB"]
              - key: isolation
                operator: Eq
                values: ["strict"]
