apiVersion: policydriven.unimi.it/v1alpha1
kind: NodeProperty
metadata:
  name: test-fail-gt-string
spec:
  levels:
    - level: 1
      disjunction:
        - clause:
            - key: some-key
              operator: Gt
              values: ["string"]