apiVersion: policydriven.unimi.it/v1alpha1
kind: NodeProperty
metadata:
  name: test-fail-missing-level
spec:
  levels:
    - disjunction:
        - clause:
            - key: some-key
              operator: Eq
              values: ["value"]