apiVersion: policydriven.unimi.it/v1alpha1
kind: NodeProperty
metadata:
  name: test-fail-duplicated-atomic-type1
spec:
  levels:
    - level: 1
      disjunction:
        - clause:
            - key: some-key
              operator: Gte
              values: [4]
        - clause:
            - key: some-key
              operator: Gte
              values: [4]