apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: dataset-service
spec:
  url: https://dataset-service.dataset-service.svc.cluster.local/datasets/validate
  timeout: 5
  caBundle: <CA_BUNDLE>

# Reponse example from the provider:
# {
#   "errors": [
#     [
#       "dnotexist",
#       "Dataset not found"
#     ]
#   ],
#   "responses": [
#     [
#       "d1",
#       {
#         "size_mb": 1024,
#         "nodes": [
#           "kind-worker2",
#           "kind-worker4",
#           "kind-worker5"
#         ],
#         "requirements": {
#           "computation": 1,
#           "security": 2
#         },
#         "contexts": ["Ford"]
#       }
#     ]
#   ],
#   "status_code": 200,
#   "system_error": ""
# }
