apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: dataset-service
spec:
  url: https://dataset-service.dataset-service.svc.cluster.local/validate
  timeout: 5
  caBundle: <CA_BUNDLE>

# Reponse example from the provider:
# {
#   "errors": [],
#   "responses": [
#     [
#       "d1",
#       {
#         "nodes": [
#           "kind-worker2",
#           "kind-worker4",
#           "kind-worker5"
#         ],
#         "requirements": {
#           "computation": 1,
#           "security": 2
#         },
#         "size_mb": 1024
#       }
#     ],
#     [
#       "d2",
#       {
#         "nodes": [
#           "kind-worker1",
#           "kind-worker4"
#         ],
#         "requirements": {
#           "computation": 3,
#           "security": 1
#         },
#         "size_mb": 2048
#       }
#     ]
#   ],
#   "status_code": 0,
#   "system_error": ""
# }

# {
#   "errors": [
#     [
#       "dnotexist",
#       "Dataset not found"
#     ]
#   ],
#   "responses": [
#     [
#       "d1",
#       {
#         "nodes": [
#           "kind-worker2",
#           "kind-worker4",
#           "kind-worker5"
#         ],
#         "requirements": {
#           "computation": 1,
#           "security": 2
#         },
#         "size_mb": 1024
#       }
#     ]
#   ],
#   "status_code": 200,
#   "system_error": ""
# }

# {
#   "errors": [
#     [
#       "dnotexist1",
#       "Dataset not found"
#     ],
#     [
#       "dnotexist2",
#       "Dataset not found"
#     ]
#   ],
#   "responses": [],
#   "status_code": 200,
#   "system_error": ""
# }
