apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: dataset-service
spec:
  url: https://dataset-service.dataset-service.svc.cluster.local/validate
  timeout: 5
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGS3pDQ0F4T2dBd0lCQWdJVUxqKzI0S083ZE01YXdiOFVwTnM3RUxKV09pY3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3SFRFYk1Ca0dBMVVFQXd3U1pHRjBZWE5sZEMxelpYSjJhV05sTFdOaE1CNFhEVEkyTURZd05USXpNamd4DQpNRm9YRFRJM01EWXdOVEl6TWpneE1Gb3dIVEViTUJrR0ExVUVBd3dTWkdGMFlYTmxkQzF6WlhKMmFXTmxMV05oDQpNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXpOWWJteTNqbTRpSFQzTkVWMmtzDQpqN2h6TWtFcU50cllkMUVOWjcrL2c4NytPa0wza2dzZW1lblN0QUhRZEhoUFh2MVlZcjhuNkRpZHZSRi9TejI2DQpualpWdVBpT0RZTmMwbGJkdVF2RWdwMXdSZGoyVTFIMEVDbW5mbnBCRUJuRElITDVRM3VlM0JleWkyNVd1UXc0DQpBeFJUblZ1bjl2NWdrMEFTbVJVRW9Hb3kzZkNwdXc4VXVqOEluNi95M3k0d3huU2lFekIyZkViL05WYlRhWXRlDQpVeS85aS9BRk41MFVUUUYwUkpIZmpNaEV0eXMrcDgxbTVHRFE3RUpqRm80aWJLL2orelN2cWNLc0tVb21RMnFlDQp3Tzc2cHcwN3dRcWlaMk9OYlpDaE4zeHFYS1g2UmVhUXpnTGFEazE0TVpKZDgxeVRrVFZqZG9VNjlFbGZ6ZlR6DQoyVHo2WXEvUlhSOEtOS0RlZGRsa2RZSzVneG56ckhUZzNBN1huMjY4a0k2U0oreG43U3duOHh5VkRjUDMxTDhrDQo3Zk5oY2paekFBY1pnb3FOUElpd3h2VVhRcGFvZUhPMnJ0TnhJaEpUL0VQOWsrS0xFcENEVDlWNTZYVDlNeTZYDQpsVnBSY0h2ekEzRG9iV2lCQjVCV0QwWnc1TCt2dmlPTDRWMW84eVZpSzlUY3BFT3RuMklnR2hqNmpGNm13NExNDQpaMis4d2w3K0tmMTFFU0x4aWpmTiszcmJxQXZycnlNSE5kREV5TFJkYWxsY2o2VjhhMGJwUmh6M2pMdC8wWjdHDQozVmdXcjFTblJQajJ0TmZGK3kyc0tzSVVWTlZYR05wMGxEUm5JNHlZR2Z4ZnVyNjlMSXhXVXovdUNMd1E2QUhkDQpYT2dRTGx0bXZBMGh6R2l3TmZISUNlVUNBd0VBQWFOak1HRXdIUVlEVlIwT0JCWUVGTTdHbDJGeXFWd3o4M001DQo0Y1J3T3NrT1dpVXpNQjhHQTFVZEl3UVlNQmFBRk03R2wyRnlxVnd6ODNNNTRjUndPc2tPV2lVek1BOEdBMVVkDQpFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnRUdNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUFFDQowZjNBV3BSeVA1czBFdmxTbDVURzJCazc5NlQzZVltSEdoN0tQRWFwTlNuSERCZG1wdkJlNkpXcjE3QWVvMnZQDQpKQ3o4elBwSlh6OVFJQ2F6cUxySTVmQmx1YXdGK0lTdjF5NVZjUjVOS0pTUEllbXZMc2VqaGxRbUpBL0RWR2k5DQp1enpuQVpMVXJaTElnMk4xeWk0QkZyeEFNbU9RVDljazZBanpyWU1RN3dWUFFlSDZhdHZZcitneVpMeHh0RVczDQpxS2FBRy9NRG5WSkJXa3FITnBQM252K2VzRmVoREJoS1dkNnJka2R6aTFCbHBabUZoT04wMHJsaXpxV2xtS284DQpqbXpMNi9BUDh6UXNkRUdvQkRnVkwwb3lORTlNMlVlTVUwV2FlQ0h4ZFZ1blRKbnFhL1NtMHB5YUNwN0dCMTA3DQovQ3NNVXpQaWEvcDlUYjJJR0l6NUV2aC9oc29FT09WRnRpZzFmd0pOZ3ZqbWVRbDBlclhpUDM1ZWlueUxiV2xODQp5ZVJjV0pYRjlKUzRPRGJ6YXhKam5QeTJjMnNxcmJ6ZG41TjRIWmdZRDVwQWhYeFhjYnNsbFJKOFc5WEtSYjlBDQphVmowN3Z3aXpDVTExdnZkWDNhREhMUjY5LzBieWZ2VWkycERoRWVuaDBBdy9qUW1Va1FSWTVmdXRYeGYwSGttDQpGcVgzM0FsM05HbFB3RGViWHlUSjUzSTA2WUtHZ0VjTGQzUWtLV1BvREh6dW1QNk1maVRzTEVBc3d3MUpFcDNQDQpJLzFEL2oxS2R4SDFHSGx0S0prT25aVWpCWXpwcXhFTG9PSmlHaXNOam5aYUs0MXVQSEc4V1hXdFVWdGl6eGFMDQp1ZlBKaHNPcmJuSmN2UUg2ek51VitVOUxKam5MVjV6ck9oZUFnQ1BDOEE9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K

# Reponse example from the provider:
# {
#   "errors": [],
#   "responses": [
#     [
#       "d1",
#       {
#         "nodes": [
#           "kind-worker2",
#           "kind-worker4",
#           "kind-worker5"
#         ],
#         "requirements": {
#           "computation": 1,
#           "security": 2
#         },
#         "size_mb": 1024
#       }
#     ],
#     [
#       "d2",
#       {
#         "nodes": [
#           "kind-worker1",
#           "kind-worker4"
#         ],
#         "requirements": {
#           "computation": 3,
#           "security": 1
#         },
#         "size_mb": 2048
#       }
#     ]
#   ],
#   "status_code": 0,
#   "system_error": ""
# }

# {
#   "errors": [
#     [
#       "dnotexist",
#       "Dataset not found"
#     ]
#   ],
#   "responses": [
#     [
#       "d1",
#       {
#         "nodes": [
#           "kind-worker2",
#           "kind-worker4",
#           "kind-worker5"
#         ],
#         "requirements": {
#           "computation": 1,
#           "security": 2
#         },
#         "size_mb": 1024
#       }
#     ]
#   ],
#   "status_code": 200,
#   "system_error": ""
# }

# {
#   "errors": [
#     [
#       "dnotexist1",
#       "Dataset not found"
#     ],
#     [
#       "dnotexist2",
#       "Dataset not found"
#     ]
#   ],
#   "responses": [],
#   "status_code": 200,
#   "system_error": ""
# }