apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      attribute.node.policydriven.unimi.it/cert: certA
      attribute.node.policydriven.unimi.it/isolation: strict
      attribute.node.policydriven.unimi.it/gpu: a100
      attribute.node.policydriven.unimi.it/cpu: 16
      topology.node.policydriven.unimi.it/location: eu-west
  - role: worker
    labels:
      attribute.node.policydriven.unimi.it/cert: certB
      attribute.node.policydriven.unimi.it/isolation: standard
      attribute.node.policydriven.unimi.it/gpu: t4
      attribute.node.policydriven.unimi.it/cpu: 8
      topology.node.policydriven.unimi.it/location: eu-north
  - role: worker
    labels:
      attribute.node.policydriven.unimi.it/cert: certC
      attribute.node.policydriven.unimi.it/isolation: standard
      attribute.node.policydriven.unimi.it/cpu: 4
      topology.node.policydriven.unimi.it/location: us-west
  - role: worker
    labels:
      attribute.node.policydriven.unimi.it/cert: certC
      attribute.node.policydriven.unimi.it/isolation: strict
      attribute.node.policydriven.unimi.it/gpu: a100
      attribute.node.policydriven.unimi.it/cpu: 24
      topology.node.policydriven.unimi.it/location: eu-south
  - role: worker
    labels:
      attribute.node.policydriven.unimi.it/cert: certA
      attribute.node.policydriven.unimi.it/isolation: strict
      attribute.node.policydriven.unimi.it/cpu: 4
      topology.node.policydriven.unimi.it/location: apac-east
