apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-fail
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine-slim
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: security-level
                operator: In
                values: ["fail"]