apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  namespace: scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-cluster-role
rules:
  # Read NodeProperties
  - apiGroups: [policydriven.unimi.it]
    resources: [nodeproperties]
    verbs: [get, list, watch]
  # Read and update nodes 
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: scheduler
roleRef:
  kind: ClusterRole
  name: scheduler-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: scheduler
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-volume
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: scheduler
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduler-extension-apiserver-authentication-reader
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: scheduler
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io