apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: policy-driven-scheduler
    plugins:
      preScore:
        enabled:
          - name: TransferScore
      score:
        enabled:
          - name: TransferScore
            weight: 1
          - name: PropScore
            weight: 1