apiVersion: v1
kind: Service
metadata:
  name: context-service
  namespace: context-service
  labels:
    app.kubernetes.io/name: context-service
spec:
  selector:
    app.kubernetes.io/name: context-service
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
