apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: emptystaticnodes
  namespace: compute
spec:
  requirements:
    security: 1
    computation: 2
  datasets:
    - d1static
    - d2static
    - d3static