apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: emptygeostar
  namespace: compute
spec:
  requirements:
    security: 1
  datasets:
    - d1 # oecd
    - d3 # us
  geo: "eu"
# eu intersection us = []
