apiVersion: policydriven.unimi.it/v1alpha1
kind: TaskRequest
metadata:
  name: taskrequest-fail
  # no namespace 'compute'
spec:
  requirements:
    security: 1
    computation: 99 # invalid level for 'computation' property
    dnotexist: 1 # non-existent property
  datasets:
    - d1
    - d2
    - dnotexist1 # non-existent dataset
    - dnotexist2 # non-existent dataset
    - dnotexistprop # dataset with "requirements": {"badprop1": 1, "badprop2": 3}
    - dnotexistlvl # dataset with "requirements": {"security": 99}