apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8svalidatetaskrequestdatasets
spec:
  crd:
    spec:
      names:
        kind: K8sValidateTaskRequestDatasets
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8svalidatetaskrequestdatasets

        dataset_list := input.review.object.spec.datasets
        property_inventory := data.inventory.cluster["policydriven.unimi.it/v1alpha1"]["NodeProperty"]
        group_inventory := data.inventory.cluster["policydriven.unimi.it/v1alpha1"]["GeographicalGroup"]

        response := external_data({
          "provider": "dataset-service",
          "keys": dataset_list
        })

        not_empty_dataset_list {
          dataset_list != null
          count(dataset_list) > 0
        }

        valid_property_level(prop_name, req_level) {
          prop := property_inventory[prop_name]
          some i
          prop.spec.levels[i].level == req_level
        }

        # ---------------------------------------------------------------------
        # Violation 1: the provider reported a system-wide failure.
        # ---------------------------------------------------------------------
        violation[{"msg": msg}] {
          not_empty_dataset_list

          response.system_error != ""

          msg := sprintf("Dataset provider system error: %v", [response.system_error])
        }

        # ---------------------------------------------------------------------
        # Violation 2: the provider reported a failure for at least one 
        # dataset.
        # ---------------------------------------------------------------------
        violation[{"msg": msg}] {
          not_empty_dataset_list

          response.system_error == ""

          some i
          error := response.errors[i]
          error != null

          msg := sprintf("Dataset error: [dataset: '%v', error: '%v']", [error[0], error[1]])
        }

        # ------------------------------------------------------------------
        # Violation 3: invalid requested property in the TaskRequest 
        # requirements of at least one dataset.
        # ------------------------------------------------------------------
        violation[{"msg": msg}] {
          not_empty_dataset_list

          response.system_error == ""

          some i
          item := response.responses[i]
          key := item[0]
          value := item[1]

          some prop_name
          value.requirements[prop_name]

          not property_inventory[prop_name]
          msg := sprintf("Dataset '%v': NodeProperty '%v' does not exist in the cluster", [key, prop_name])
        }

        # ------------------------------------------------------------------
        # Violation 4: invalid level for an existing property in the
        # TaskRequest requirements of at least one dataset.
        # ------------------------------------------------------------------
        violation[{"msg": msg}] {
          not_empty_dataset_list

          response.system_error == ""

          some i
          item := response.responses[i]
          key := item[0]
          value := item[1]

          some prop_name
          req_level := value.requirements[prop_name]
          req_level != 0

          property_inventory[prop_name]

          not valid_property_level(prop_name, req_level)
          msg := sprintf("Dataset '%v': NodeProperty '%v' exists, but level '%v' is not defined", [key, prop_name, req_level])
        }

        # ---------------------------------------------------------------------
        # Violation 5: dataset geo refers to a GeographicalGroup that does not 
        # exist
        # ---------------------------------------------------------------------
        violation[{"msg": msg}] {
          not_empty_dataset_list

          response.system_error == ""

          some i
          item := response.responses[i]
          key := item[0]
          value := item[1]

          geo := value.geo
          geo != null

          not group_inventory[geo]

          msg := sprintf("Dataset '%v': GeographicalGroup '%v' does not exist in the cluster", [key, geo])
        }
