from src.config import (
    Config,
    DATASET_SERVICE_URL_DEFAULT,
    GEOGRAPHICAL_GROUPS_PLURAL_DEFAULT,
    GROUP_DEFAULT,
    NODE_TOPOLOGY_LOCATION_LABEL_DEFAULT,
    TASK_NAMESPACE_DEFAULT,
    TASK_REQUESTS_PLURAL_DEFAULT,
    VERSION_DEFAULT,
    TASK_REQUEST_KIND_DEFAULT,
    JOB_LABEL_PREFIX_DEFAULT,
    JOB_ANNOTATION_PREFIX_DEFAULT,
    TASK_REQUEST_REF_LABEL_DEFAULT,
    BETA_STAR_ANNOTATION_DEFAULT,
    GEO_STAR_ANNOTATION_DEFAULT,
    CTX_STAR_ANNOTATION_DEFAULT,
    DATASETS_ANNOTATION_DEFAULT,
    ISSUER_ANNOTATION_DEFAULT,
    NODE_PROPERTY_PREFIX_DEFAULT,
    SCHEDULER_NAME_DEFAULT,
)


def make_config() -> Config:
    return Config(
        group=GROUP_DEFAULT,
        version=VERSION_DEFAULT,
        task_requests_plural=TASK_REQUESTS_PLURAL_DEFAULT,
        geographical_groups_plural=GEOGRAPHICAL_GROUPS_PLURAL_DEFAULT,
        task_namespace=TASK_NAMESPACE_DEFAULT,
        dataset_service_url=DATASET_SERVICE_URL_DEFAULT,
        dataset_service_ca_file=None,
        task_request_kind=TASK_REQUEST_KIND_DEFAULT,
        job_label_prefix=JOB_LABEL_PREFIX_DEFAULT,
        job_annotation_prefix=JOB_ANNOTATION_PREFIX_DEFAULT,
        task_request_ref_label=TASK_REQUEST_REF_LABEL_DEFAULT,
        beta_star_annotation=BETA_STAR_ANNOTATION_DEFAULT,
        geo_star_annotation=GEO_STAR_ANNOTATION_DEFAULT,
        ctx_star_annotation=CTX_STAR_ANNOTATION_DEFAULT,
        datasets_annotation=DATASETS_ANNOTATION_DEFAULT,
        issuer_annotation=ISSUER_ANNOTATION_DEFAULT,
        node_property_prefix=NODE_PROPERTY_PREFIX_DEFAULT,
        node_topology_location_label=NODE_TOPOLOGY_LOCATION_LABEL_DEFAULT,
        scheduler_name=SCHEDULER_NAME_DEFAULT,
        log_level="WARNING",
    )
